version: "3"
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    build: ./client
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=3000"

  api:
    build: ./api
    ports:
      - 3030:3030
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.port=3030"
