version: 2
jobs:
  build:
    docker:
      - image: jockee/circlebase:latest
    steps:
      - setup_remote_docker:
          reusable: true
      - checkout
      - run:
          name: Building images
          command: make build
      - run:
          name: Starting containers
          command: make up
      - deploy:
          name: Deploying
          command: |
            printf '%s\n    %s\n' 'Host *' 'StrictHostKeyChecking no' >> ~/.ssh/config
            make deploy
