export const chart: string;
export const grid: string;
export const xGrid: string;
export const yGrid: string;
export const dataPoint: string;
export const timeLine: string;
export const selected: string;
export const legend: string;
export const noData: string;
